### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by pramithready** [b4nguyen/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Nice work with the report!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by pramithready** [comment]
Nice job fixing some of the previous problems! We still want you to provide a markdown formatted link in this report, so you can format the VS Code download link in markdown. Additionally, we want a total count of the number of keystrokes it took you to optimally run the remote commands

**Comment by b4nguyen** [comment]
Hi, I believe I have fixed the last two problems. The regrade requests closed, so I don't really know what to do now. I'm just commenting here to try to let you know that it's been fixed.

**Comment by pramithready** [comment]
Great work! Your grade has been updated
